### ISSUE TITLE
No such file or directory: .../data/ORDO_en_4.2.owl

### ISSUE THREAD

**Issue by guanchuwang** [PittNAIL/llms-vote#1]
This is fantastic work for rare disease identification, which takes advantage of the emergency of LLM in the healthcare domain!

Could you tell us whether the ORDO_en_4.2.owl file is necessary to generate the list of rare diseases? If so, could you consider sharing this file?

**Comment by oniani** [comment]
Hi Guanchu — thank you!

Yes, the file is necessary.
Here is the download link: https://www.orphadata.com/data/ontologies/ordo/previous_versions/ordo_orphanet_4.2.owl.zip

**Comment by guanchuwang** [comment]
> Hi Guanchu — thank you!
> 
> Yes, the file is necessary. Here is the download link: https://www.orphadata.com/data/ontologies/ordo/previous_versions/ordo_orphanet_4.2.owl.zip

It works. Thanks very much! :)
